# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
name: $(Year:yy)$(DayOfYear).$(Rev:r)

trigger:
  branches:
    include:
      - master
      - "release/*"
      - "staging/*"

variables:
# must be created in the azure UI under Pipelines > Library and specify accessKey, secretKey, region, and bucket
- group: 's3-public-bucket-upload'
# Provides: P12_PASSWORD, SIGNING_IDENTITY, SIGNING_IDENTITY_FILENAME, ALTOOL_USERNAME, ALTOOL_APP_PASSWORD
- group: 'osx-signing'
- name: sdk
  value: macosx
- name: xcodeVersionNum
  value: 11
- name: configuration
  value: 'Release'
- name: workspacePath
  value: '**/MorphicLite.xcworkspace'
- name: finalVersion
  value: '0.$(Build.BuildNumber)'
# This means the pipeline will configure all signing options
- name: signingOption
  value: 'default' # this setting uses the builtin project configuration options for signing
- name: extraArgs
  value: 'OTHER_CODE_SIGN_FLAGS="--timestamp" CURRENT_PROJECT_VERSION="$(Build.BuildNumber)"'

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'raising_the_floor_5AAXYGZ428.p12'
    certPwd: '$(P12_PASSWORD)'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'Morphic_Configurator_for_macOS.provisionprofile'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'Morphic_Client_for_macOS.provisionprofile'

- task: Xcode@5
  displayName: Build MorphicCore
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicCore'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
    signingOption: '$(signingOption)'
    args: '$(extraArgs)'
- task: Xcode@5
  displayName: Build MorphicService
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicService'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
    signingOption: '$(signingOption)'
    args: '$(extraArgs)'
- task: Xcode@5
  displayName: Build MorphicSettings
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicSettings'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
    signingOption: '$(signingOption)'
    args: '$(extraArgs)'
- task: Xcode@5
  displayName: Build MorphicConfigurator
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicConfigurator'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
    signingOption: '$(signingOption)'
    args: '$(extraArgs)'
- task: Xcode@5
  displayName: Build Morphic
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'Morphic'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
    signingOption: '$(signingOption)'
    args: '$(extraArgs)'
- task: Bash@3
  displayName: notarize dmg
  env:
    BRANCH: $(Build.SourceBranch)
    BRANCH_NAME: $(Build.SourceBranchName)
    USERNAME: '$(ALTOOL_USERNAME)'
    APP_PASSWORD: '$(ALTOOL_APP_PASSWORD)'
    SIGNING_IDENTITY: '$(SIGNING_IDENTITY)'
  inputs:
    targetType: 'filePath'
    filePath: dmg-notarize.sh
- task: Bash@3
  displayName: publish to s3
  env:
    AWS_ACCESS_KEY_ID: $(accessKey)
    AWS_SECRET_ACCESS_KEY: $(secretKey)
    BUCKET: $(bucket)
    AWS_DEFAULT_REGION: $(region)
    BRANCH: $(Build.SourceBranch)
    BRANCH_NAME: $(Build.SourceBranchName)
    VERSION: '$(finalVersion)'
  inputs:
    targetType: 'filePath'
    filePath: push-to-s3.sh
