# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
      - master
      - develop
  tags:
    include:
      - "v*"

variables:
# must be created in the azure UI under Pipelines > Library and specify accessKey, secretKey, region, and bucket
- group: 's3-public-bucket-upload'
- name: sdk
  value: macosx
- name: xcodeVersionNum
  value: 11
- name: configuration
  value: 'Release'
- name: workspacePath
  value: '**/MorphicLite.xcworkspace'
  # The major version for semver in the client (X in X.Y.Z)
- name: majorVersion
  value: '0'

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  displayName: "update plist versions"
  inputs:
    targetType: filePath
    filePath: set-version.sh
    arguments: "$(majorVersion).$(Build.BuildNumber)"
- task: Xcode@5
  displayName: Build MorphicCore
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicCore'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
- task: Xcode@5
  displayName: Build MorphicService
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicService'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
- task: Xcode@5
  displayName: Build MorphicConfigurator
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicConfigurator'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
- task: Xcode@5
  displayName: Build MorphicSettings
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicSettings'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
- task: Xcode@5
  displayName: Build Morphic
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'Morphic'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
    useXcpretty: false
- task: Bash@3
  displayName: publish to s3
  env:
    AWS_ACCESS_KEY_ID: $(accessKey)
    AWS_SECRET_ACCESS_KEY: $(secretKey)
    BUCKET: $(bucket)
    AWS_DEFAULT_REGION: $(region)
    BRANCH: $(Build.SourceBranch)
    BRANCH_NAME: $(Build.SourceBranchName)
  inputs:
    targetType: 'inline'
    script: |
      set -e
      set -x

      CLIENT_NAME=""
      if [[ "${BRANCH_NAME}" == "master" ]]; then
        CLIENT_NAME="Morphic.dmg"
      fi
      if [[ "${BRANCH_NAME}" == "develop" ]]; then
        CLIENT_NAME="Morphic-latest.dmg"
      fi
      if [[ "${BRANCH}" == *"tags"* ]]; then
        CLIENT_NAME="Morphic-${BRANCH_NAME}.dmg"
      fi
      if [[ "$CLIENT_NAME" == "" ]]; then
        #echo "no client name found. will not publish to s3"
        #exit 0
        CLIENT_NAME="Morphic-test.dmg"
      fi

      # seems to be installed already
      # ref: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
      aws s3 cp Morphic/Morphic.dmg s3://${BUCKET}/osx/$CLIENT_NAME