# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

variables:
  sdk: macosx
  xcodeVersionNum: 11
  configuration: 'Release'
  workspacePath: '**/MorphicLite.xcworkspace'
  # The major version for semver in the client (X in X.Y.Z)
  majorVersion: '0'

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  displayName: "update plist versions"
  inputs:
    targetType: filePath
    filePath: set-version.sh
    arguments: "$(majorVersion).$(Build.BuildNumber)"
- task: Xcode@5
  displayName: Build MorphicCore
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicCore'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build MorphicService
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicService'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build MorphicConfigurator
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicConfigurator'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build MorphicSettings
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'MorphicSettings'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
- task: Xcode@5
  displayName: Build Morphic
  inputs:
    actions: 'build'
    sdk: $(sdk)
    scheme: 'Morphic'
    configuration: '$(configuration)'
    xcWorkspacePath: '$(workspacePath)'
    xcodeVersion: $(xcodeVersionNum)
- task: Bash@3
  displayName: debug
  inputs:
    targetType: inline
    script: |
      find . -iname '*.dmg'